spring.application.name=hackathon_29_05_2026_012
# confige datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/hackathon_29_05_2026_012?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=141248690405Zt.

# confige JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

#config  pagination
pageSize = 3


# # config log
# logging.level.root=info
# logging.level.com.example.demo07aspect.controller=warn
# logging.level.com.example.demo07aspect.service=error
# logging.level.org.springframework=warn
# logging.file.name=logs/application.log
# logging.logback.rollingpolicy.max-history=30
# logging.logback.rollingpolicy.max-file-size = 100MB
# logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss:SSS} %-5level %logger{39} %msg%n